# Generated by Django 3.0.8 on 2020-08-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200822_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='foodtypes',
            field=models.CharField(choices=[('Vegetarian', 'Veg'), ('Non-Vegetarian', 'Non-Veg')], default='Vegetarian', max_length=100),
            preserve_default=False,
        ),
    ]
