# Generated by Django 3.0.8 on 2020-08-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_foodtypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='foodtypes',
            field=models.CharField(choices=[('Vegetarian', 'Veg'), ('Non-Vegetarian', 'Non-Veg'), ('Raw-Foods', 'RW'), ('Non-Raw-Foods', 'NRF'), ('Fruits', 'F'), ('Whole-Grain', 'WG'), ('Dairy-Products', 'DP'), ('Legumes/Beans', 'L/B'), ('Breads', 'B'), ('Rice/Brown-Rice', 'R/B-R'), ('Cooked-Veg', 'CV'), ('Cooked-Non-veg', 'CNV')], max_length=100),
        ),
    ]
